### ISSUE TITLE
Efficient Way to compare single image with bulk images in a system

### ISSUE THREAD

**Issue by sujitpranavreddy** [toy/pHash#12]
Is there any efficient built-in method in pHash to compare a single with bulk images in a system ?

**Comment by toy** [comment]
This gem gives you the ability to calculate a hash for each image and to compare the hashes. No file system traversing.
But there is `Find.find` in ruby to find all files. You can distinguish images by extension or using magic number detection. Then calculate a hash for each and compare to the hash of original image.

**Comment by sujitpranavreddy** [comment]
the problem is i have all the images in s3 and now i want to compare an image which is being uploaded with all the images which belong to a particular entity. As of now, there are 70k images and it will increase gradually. Will there be a scalability problem? what if it is calculating hashes for 100k images and comparing. Will it not take time?

**Comment by toy** [comment]
I've perceived the problem to be more local. Just storing generated hashes and getting hamming distance from each to a new one will not scale.
So pHash gives you hashes, but it doesn't have a builtin way to efficiently find similar images in big sets. But quick search shows that there are several solutions on how to make searching by hamming distance scalable.

**Comment by sujitpranavreddy** [comment]
Thanks @toy !!
