### ISSUE TITLE
Database storage & comparison?

### ISSUE THREAD

**Issue by Sudrien** [toy/pHash#13]
Is there a standard way to store a pHash to activerecord? I have about a gig of images to check against during new uploads, and I have to believe checking against stored values would be less resource intensive.

If I'm reading the code correctly, the only way to compare hashes is creating new instances from paths.

**Comment by toy** [comment]
An image phash is an unsigned 64-bit number. The gem is using fair amount of metaprogramming, so here is the way:
```ruby
# get the `Phash::ImageHash` wrapper
phash = Phash::Image.new('spec/data/mouse-1-120.png').phash
# or more directly
phash = Phash.image_hash('spec/data/mouse-1-120.png')

# get the fingerprint number
number = phash.data

# store/retrieve

# reconstruct the wrapper
phash = Phash::ImageHash.new(number)
```

Please read also #12 about efficiency.

**Comment by Nakilon** [comment]
@Sudrien just in case you need to store some weird objects of any kind you always can use Ruby's module `Marshal` -- it serialises objects to some binary stuff, that can be then deserialised (if you require the same game to make your interpreter runtime know what's that).
