### ISSUE TITLE
Could not open library '/usr/local/lib/libpHash.dylib' on Mac OS El Captain

### ISSUE THREAD

**Issue by Nakilon** [toy/pHash#8]
On `require "phash/image"` I get
```
/Users/nakilon/.gem/gems/ffi-1.9.14/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library '/usr/local/lib/libpHash.dylib': dlopen(/usr/local/lib/libpHash.dylib, 5): image not found (LoadError)
	from /Users/nakilon/.gem/gems/ffi-1.9.14/lib/ffi/library.rb:100:in `map'
	from /Users/nakilon/.gem/gems/ffi-1.9.14/lib/ffi/library.rb:100:in `ffi_lib'
	from /Users/nakilon/.gem/gems/pHash-1.1.5/lib/phash.rb:59:in `<module:Phash>'
	from /Users/nakilon/.gem/gems/pHash-1.1.5/lib/phash.rb:3:in `<top (required)>'
	from /Users/nakilon/.gem/gems/pHash-1.1.5/lib/phash/image.rb:1:in `require'
	from /Users/nakilon/.gem/gems/pHash-1.1.5/lib/phash/image.rb:1:in `<top (required)>'
```

Mac OS 10.11.6
pHash (1.1.5)
ruby 2.0.0p648

**Comment by toy** [comment]
The error is from ffi saying that the dylib file is not there.
It looks like you've set `PHASH_LIB` to `/usr/local/lib/libpHash.dylib`.
So you need to check where is the `libpHash.dylib`.

**Comment by Nakilon** [comment]
I didn't have pHash lib neither in /usr/bin not in /usr/local/bin so I took Homebrew, but formula is deleted, because of https://github.com/Homebrew/legacy-homebrew/commit/a52f48bf27f4434fb40cfe854ed13c66e8391344
It really has some issue:
```*** Configuring image hash ***

checking CImg.h usability... no
checking CImg.h presence... no
checking for CImg.h... no
checking whether CImg.h is in the current or src directory.... no

*** Configuring video Hash ***

checking whether FFmpeg is present... checking for avcodec_alloc_frame in -lavcodec... no
configure: error: 

*** libavcodec not found.
You need FFmpeg. Get it at <http://ffmpeg.org/>```

But since I need it only for images, this worked for me:
```
brew install --without-video-hash homebrew/boneyard/phash
```

**Comment by Nakilon** [comment]
See also: https://github.com/Homebrew/legacy-homebrew/pull/49178

**Comment by Nakilon** [comment]
Hmmm... I don't think pHash works correctly since my update to El Captain, because it started giving false 1.0 similarity to pretty different images:

http://static1.squarespace.com/static/546d6314e4b0dce5377a07f3/54f7ad0ce4b0aea85187fcc9/54f7ad34e4b0aea851882685/1425518500367/
http://static1.squarespace.com/static/546d6314e4b0dce5377a07f3/54f7ad0ce4b0aea85187fcc9/54f7ad3ae4b0aea851882c90/1425518468940/

**Comment by Nakilon** [comment]
Issue happens only when one of image is PNG!
If you convert both above to JPEG, you'll get 0.46875.

**Comment by toy** [comment]
The problem with comparing PNG images is in pHash library.
I've tried to contact the authors long time ago including patches, but never got a reply from them.
You can check patches in macports repository: https://trac.macports.org/browser/trunk/dports/multimedia/pHash/files
The fix for PNG images is in [patch-pHash.cpp.diff](https://trac.macports.org/browser/trunk/dports/multimedia/pHash/files/patch-pHash.cpp.diff).

If you need to compare only images, I can suggest to try [`phamilie` gem](https://github.com/toy/phamilie) which I've created by replacing comparison algorithm of [`similie` gem](https://github.com/deepfryed/similie).

**Comment by Nakilon** [comment]
This is my current workaround:
```
      Phash.image_hash( if ".png" == File.extname(filename)
        `sips -s format jpeg #{filename} --out temp.jpg`
        "temp.jpg"
      else
        filename
      end )
```

**Comment by Nakilon** [comment]
@toy I was reviewing manually similarities >0.75, but pHash gave only 0.46 for these two images (1 set):  
* http://static1.squarespace.com/static/546d6314e4b0dce5377a07f3/54f7ad0ce4b0aea85187fcc9/54f7ad25e4b0aea8518814e9/1425518719697/?format=4999w
* http://static1.squarespace.com/static/546d6314e4b0dce5377a07f3/54f7ad0ce4b0aea85187fcc9/54f7ad25e4b0aea8518814e9/1425518719697/?format=4999w

So I gave phamilie a try -- it did well on (2 set):
* https://c5.staticflickr.com/9/8004/7692104828_55cb55b45b_k.jpg
* http://static1.squarespace.com/static/546d6314e4b0dce5377a07f3/54f7ad0ce4b0aea85187fcc9/54f7ad34e4b0aea851882547/1425518794812/?format=4999w
giving 2 (pHash gives 0.97), but it can't compare (1 set) too -- gives 28.

**Comment by toy** [comment]
phamilie uses algorithm from pHash, so except the bug with 32 bit images in pHash, they should give similar result. pHash gem also converts the bit_difference like `(1 - bit_difference / 64.0)`.

The problem with set 1 is that first image is part of second image, but they are not similar for the algorithm as it "fingerprints" complete images and does not try to find subsets. Algorithm easily detects resized images, images with changed contrast or some colour manipulation, or minimal cropping.

**Comment by Nakilon** [comment]
I gave Google Vision a try -- it retrieves features from images in a form of English words. Had to think up a formula to measure a similarity from it. It did very well with the (set 1), so a mix of this metric with pHash metric gave nice results for my needs.
